spring.application.name=BookManagementSystem

# Ensure dynamic port binding
server.port=${PORT:8080}

# Disabling database auto-configuration as I am not using any database
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration